### ISSUE TITLE
better log-sum-exp approximation

### ISSUE THREAD

**Issue by pajkossy** [zseder/hunvec#52]
log(sum(exp(z_{i}))) = max_{i}z_{i} + log(sum(z_{i} - max{i}z_{i}))

**Comment by zseder** [comment]
I implemented it, but we'll have to cite it somehow in the code. Where does it come from?

**Comment by zseder** [comment]
isn't there an exp() somewhere in the equation?

**Comment by pajkossy** [comment]
well, you're right it should be max_{i}z_{i} + log(exp(sum(z_{i} - max{i}z_{i})))
(and it is not just an approximation)
I took it from Hugo Larochelle's slide (University of Sherkbrooke, Neural Networks course), 
but I guess it's usage is so common, that we don't have to cite is

**Comment by zseder** [comment]
done in final commit https://github.com/zseder/hunvec/commit/8d0690e44429a3fcebcfed8dba167bbfcf33103f
