### ISSUE TITLE
dropout not working when model is reloaded and training is continued

### ISSUE THREAD

**Issue by zseder** [zseder/hunvec#61]
in `sequence_tagger.py`, `dropout_fprop()` uses `self.hdims`, but that parameter isn't saved with the model (see `__get_state__`), so it fails. 
Instead of checking `hdims`, a check on `self.layers` would be better of possible. If not, `hdims` has to go to `__get_state__`, but hopefully not, it is redundant.

@pajkossy

**Comment by zseder** [comment]
check `self.tagger.layers`, that will be easy

**Comment by pajkossy** [comment]
solved by #62
